import Header from "@/components/Header";
import Slider from "@/components/Slider";
import Head from "next/head";

// import { getSession, useSession } from "next-auth/react";
import MovieLibrary from "@/components/MovieLibrary";
import ShowLibrary from "@/components/ShowLibrary";
import Hero from "@/components/Hero";

export default function Home({
  popularMovies,
  popularShows,
  topRatedMovies,
  topRatedShows,
  airingTodayShows,
  upcommingMovies,
}) {
  // const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {/* {!session ? (
        <Hero />
      ) : ( */}
      <main className="relative min-h-screen after:bg-home after:bg-center after:bg-cover after:bg-no-repeat after:bg-fixed after:absolute after:inset-0 after:z-[-1]">
        <Slider />
        {/* Could be one Collection */}
        <MovieLibrary results={popularMovies} title="Popular Movies" />
        <MovieLibrary results={topRatedMovies} title="Top Rated Movies" />
        <MovieLibrary results={upcommingMovies} title="Upcomming Movies" />

        <ShowLibrary results={popularShows} title="Popular Shows" />
        <ShowLibrary results={topRatedShows} title="Top Rated Shows" />
        <ShowLibrary results={airingTodayShows} title="Airing Today Shows" />
      </main>
      {/* )} */}
    </>
  );
}

export async function getServerSideProps(context) {
  // const session = await getSession(context);

  const [
    popularMovies,
    popularShows,
    topRatedMovies,
    topRatedShows,
    airingTodayShows,
    upcommingMovies,
  ] = await Promise.all([
    fetch(
      `https://api.themoviedb.org/3/movie/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ).then((result) => result.json()),
    fetch(
      `https://api.themoviedb.org/3/tv/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ).then((result) => result.json()),
    fetch(
      `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ).then((result) => result.json()),
    fetch(
      `https://api.themoviedb.org/3/tv/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ).then((result) => result.json()),
    fetch(
      `https://api.themoviedb.org/3/tv/on_the_air?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ).then((result) => result.json()),
    fetch(
      `https://api.themoviedb.org/3/movie/upcoming?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ).then((result) => result.json()),
  ]);

  return {
    props: {
      // session,
      popularMovies: popularMovies.results,
      popularShows: popularShows.results,
      topRatedMovies: topRatedMovies.results,
      topRatedShows: topRatedShows.results,
      airingTodayShows: airingTodayShows.results,
      upcommingMovies: upcommingMovies.results,
    },
  };
}
